//
// Quadratic Approximation Unit (QAU) Verilator C++ Testbench (Legacy Support)
//

#include <iostream>
#include <iomanip>
#include <deque>

#include "Quadra.hpp" // C++ model (reference)
#include "verilated.h" // Verilated RTL

#ifdef VM_TRACE
#include <verilated_vcd_c.h>
#endif

#include "Vquadra_top.h" // auto-generated by Verilator

const uint32_t T_HALF_CLOCK = 500; // [time precision units] = 500ps for 1ps precision
const uint32_t EM_LATENCY   = 8;   // [cycles]

// Global time variable for legacy Verilator versions
vluint64_t main_time = 0;
double sc_time_stamp() { return main_time; }

// --------------------------------------------------------------------------------

inline void vmTrace(VerilatedVcdC* trace_fp)
{
#if VM_TRACE
    if (trace_fp)
        trace_fp->dump(main_time);
#endif
}

inline void atNegEdgeHalfClk(Vquadra_top* top, VerilatedVcdC* trace_fp)
{
    top->clk = 0;
    main_time += T_HALF_CLOCK;
    top->eval();
    vmTrace(trace_fp);
}

inline void atPosEdgeHalfClk(Vquadra_top* top, VerilatedVcdC* trace_fp)
{
    top->clk = 1;
    main_time += T_HALF_CLOCK;
    top->eval();
    vmTrace(trace_fp);
}

inline void atPosEdgeClk(Vquadra_top* top, VerilatedVcdC* trace_fp)
{
    atNegEdgeHalfClk(top, trace_fp);
    atPosEdgeHalfClk(top, trace_fp);
}

inline void genReset(Vquadra_top* top, VerilatedVcdC* trace_fp, const vluint64_t& clock_cntr)
{
    top->rst_b = (clock_cntr == 1) ? 0 : 1;
    top->clk = 0;
    main_time += T_HALF_CLOCK;
    top->eval();
    vmTrace(trace_fp);

    top->clk = 1;
    main_time += T_HALF_CLOCK;
    top->eval();
    vmTrace(trace_fp);
}

// --------------------------------------------------------------------------------

inline void checkOutput(Vquadra_top* top, std::deque<x_fxd_t>& lat_fifo)
{
    if (top->y_dv == 0 || lat_fifo.empty()) return;
    x_fxd_t x_fxd = lat_fifo.front(); lat_fifo.pop_front();

    int32_t raw_y = top->y & 0x1FFFFFF; 

    // Sign extension for 25
    if (raw_y & (1 << 24)) {
        raw_y |= 0xFF000000; 
    }

    // Divide by 2^23
    double y_rtl_dbl = (double)raw_y / (double)(1LL << 23);
    double x_dbl = x_fxd.to_double();
    double y_ref = sin((2.0 * x_dbl) - (M_PI / 4.0));
    double delta = abs(y_rtl_dbl - y_ref);

    if (delta < 2.15e-6) {
        //SUCCES
    } 

    else {
        std::cout << "[FAIL] Delta: " << std::scientific << delta << std::endl;
        std::cout << "       RTL: " << y_rtl_dbl << " | REF: " << y_ref << std::endl;
        std::cout << "       HEX: 0x" << std::hex << (top->y & 0x1FFFFFF) << std::dec << std::endl;
    }
}

void testQuadra(Vquadra_top* top, VerilatedVcdC* trace_fp, std::deque<x_fxd_t>& lat_fifo, vluint64_t& clock_cntr)
{
    using namespace std;

    uint32_t x_start = 0xfffff0;
    uint32_t x_stop  = 0xffffff;
    uint32_t x_step  = 0x000001;

    for (uint32_t x = x_start; x <= x_stop; x += x_step)
    {
        x_int_t x_int = x;
        x_fxd_t x_fxd = 0;
        x_fxd.set_slc(0, x_int);

        lat_fifo.push_back(x_fxd);

        top->x    = x;
        top->x_dv = 1;

        atPosEdgeClk(top, trace_fp);
        clock_cntr++;
        checkOutput(top, lat_fifo);
    }

    for (uint32_t i = 0; i < 5; i++)
    {
        top->x    = 0.0;
        top->x_dv = 0;

        atPosEdgeClk(top, trace_fp);
        clock_cntr++;
        checkOutput(top, lat_fifo);
    }

    uint64_t lat_fifo_size = lat_fifo.size();
    if (lat_fifo_size > 0)
        cout << endl << "Latency fifo contains " << lat_fifo_size << " sample(s)." << endl;
}

// --------------------------------------------------------------------------------

int main(int argc, char* argv[], char* env[])
{
    using namespace std;

    Verilated::commandArgs(argc, argv);
    Verilated::debug(0);
    Verilated::randReset(2);

    Vquadra_top* top = new Vquadra_top;

    VerilatedVcdC* trace_fp = nullptr;
#if VM_TRACE
    Verilated::traceEverOn(true);
    trace_fp = new VerilatedVcdC;
    top->trace(trace_fp, 5);
    trace_fp->open("dump.vcd");
#endif

    vluint64_t clock_cntr = 0;

    top->clk      = 0;
    top->rst_b    = 1;
    top->x        = 0;
    top->x_dv     = 0;

    deque<x_fxd_t> lat_fifo;

    for (; clock_cntr < 10; clock_cntr++)
        genReset(top, trace_fp, clock_cntr);

    for (uint32_t i = 0; i < 5; i++, clock_cntr++)
        atPosEdgeClk(top, trace_fp);

    testQuadra(top, trace_fp, lat_fifo, clock_cntr);

    cout << endl << "Testbench ran for " << clock_cntr << " clocks." << endl;

    top->final();

#if VM_TRACE
    if (trace_fp) {
        trace_fp->close();
        delete trace_fp;
    }
#endif

    delete top;
    return 0;
}